/*4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/
package day2.part3;



import java.util.Scanner;

public class Question4 {

	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		String s=sc.nextLine();
		String t=sc.nextLine();
		int sumOfS=0;
	    int sumOfT=0;
	    for(int i=0;i<s.length();i++){
	       sumOfS+=s.charAt(i);
	       sumOfT+=t.charAt(i);
	     }
	     sumOfT+=t.charAt(t.length()-1);
	     System.out.println((char)(sumOfT-sumOfS));
	     sc.close();
	}

}